version: '3.7'

services:
  hugo:
    build: .
    image: hugo-docker
    container_name: hugo_docker
    entrypoint: bash
    ports:
      - "1313:1313"
    volumes:
      - "./:/src/"
    tty: true
    working_dir: /src/