name: 自由に記事を書く
description: 自由に記事を書きたい場合はこのテンプレートを利用してください。
title: "ここに記事タイトルを入力"
labels: ["article", "free"]
assignees:
  - octocat

body:
  - type: input
    id: permalink
    attributes:
      label: パーマリンク
      description: |
        パーマリンクを設定してください。記事のタイトルに関連したパーマリンクを設定しましょう。
        例）記事のタイトル「IEEE SSCI 2021に参加しました」　→　パーマリンク「attend-ieee-ssci-2021」
      placeholder: ex. attend-ieee-2021
    validations:
      required: true
  
  - type: textarea
    id: contents
    attributes:
      label: 本文
      description: |
        記事の本文を入力してください。
    validations:
      required: true
