name: Submit free
description:
title: "ここに記事タイトルを入力"
labels: ["article", "free"]
assignees:
  - octocat
body:
  - type: textarea
    id: contents
    attributes:
      label: 本文
      description: |
        記事の本文を入力してください。
    validations:
      required: true
