name: article-apply

on:
  push:
    branches:
      - main

jobs:
  article-apply:
    runs-on: ubuntu-18.04
    steps:
      # checkout to the commit that has been pushed
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      # Apply articles to Article DB
      - name: Apply articles to Article DB
        run: |
          python3 ./scripts/article_apply.py ./db/articles.json

      # push
      - name: Push
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add ./db/
          git diff --exit-code -- ./db/articles.json
          if [[ $? -eq 1 ]]; then
            git commit -m "記事DBを更新";
            git push origin HEAD:${GITHUB_REF};
          fi
