name: post-article
on:
  issues:
    types:
      - opened
      - edited
env:
  article_file: ./mysite/content/news/'${{ github.event.issue.number }}'.md

jobs:
  post-article:
    runs-on: ubuntu-18.04
    if: ${{ contains(github.event.issue.labels.*.name, 'article') }} # Only process issues with the 'article' label
    steps:
      # Checkout to the commit that has been pushed
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      # Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"
          extended: true

      # Create article
      - name: Create article
        run: |
          if [ ! -e '${{ article_file }}' ]; then
            touch '${{ article_file }}'
          fi
      
      # Update article
      - name: Update article
        run: |
          echo "+++' >> '${{ article_file_path }}'
          echo "title = '${{ github.event.issue.title }}'" >> '${{ article_file_path }}'
          echo "date = {{ .Date }}" >> '${{ article_file_path }}'
          echo "categories = [\"\"]" >> '${{ article_file_path }}'
          echo "draft = false" >> '${{ article_file_path }}'
          echo "+++" >> '${{ article_file_path }}'
          echo -e "'${{ github.event.issue.body }}'" >> '${{ article_file_path }}'
          
      - name: check article file
        run: |
          cat '${{ article_file_path }}'
          
#       # write body
#       - name: Write body
#         run: |
#           echo -e "'${{ github.event.issue.body }}'" >> ./mysite/content/news/'${{ github.event.issue.title }}'.md

#       # push
#       - name: Push
#         run: |
#           git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
#           git config --global user.name "${GITHUB_ACTOR}"
#           git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#           git add ./mysite/content/news/; \
#           git commit -m "記事を追加"; \
#           git push origin HEAD:${GITHUB_REF}; \
