name: post-article
on:
  issues:
    types:
      - opened
      - edited
env:
  article_file: ./mysite/content/news/${{ github.event.issue.number }}.md

jobs:
  post-article:
    runs-on: ubuntu-18.04
    if: ${{ contains(github.event.issue.labels.*.name, 'article') }} # Only process issues with the 'article' label
    steps:
      # Checkout to the commit that has been pushed
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      # Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"
          extended: true

      # Create article
      - name: Create article
        run: |
          if [ ! -e ${{ env.article_file }} ]; then
            touch ${{ env.article_file }}
          fi
          
      # Update article
      - name: Update article
        run: |
          echo '+++' >> ${{ env.article_file }}
          echo 'title = ${{ github.event.issue.title }}' >> ${{ env.article_file }}
          echo 'date = {{ .Date }}' >> ${{ env.article_file }}
          echo 'categories = [""]' >> ${{ env.article_file }}
          echo 'draft = false' >> ${{ env.article_file }}
          echo '+++' >> ${{ env.article_file }}
          echo -e '${{ github.event.issue.body }}' >> ${{ env.article_file }}

      - name: debug
        run: |
          sed -e s/"'"/'\'"\'"/g '${{ github.event.issue.body }}' >> ${{ env.article_file }}

      - name: check article file
        run: |
          cat ${{ env.article_file }}

#       # push
#       - name: Push
#         run: |
#           git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
#           git config --global user.name "${GITHUB_ACTOR}"
#           git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#           git add ./mysite/content/news/; \
#           git commit -m "記事を追加"; \
#           git push origin HEAD:${GITHUB_REF}; \
