name: Post article to blog

on:
  issues:
    types: [opened, edited]

jobs:
  post:
    runs-on: ubuntu-18.04
    steps:
      - name: Get issue
        run: |
          echo "test"
          echo {{ github.event.issue.title }}
